/* Bova Core Control Center · v2.7.13 */
const C=()=>window.BOVA_CONFIG||{roles:[],channels:[],hosts:[],servers:[],emojis:[]};
const TZ_LIST=[
 {id:"America/Sao_Paulo",label:"São Paulo (UTC-3)",offset:-3},{id:"UTC",label:"UTC",offset:0},
 {id:"America/New_York",label:"New York (UTC-5)",offset:-5},{id:"America/Los_Angeles",label:"Los Angeles (UTC-8)",offset:-8},
 {id:"Europe/London",label:"London (UTC+0)",offset:0},{id:"Europe/Paris",label:"Paris (UTC+1)",offset:1},{id:"Asia/Tokyo",label:"Tokyo (UTC+9)",offset:9}
];

function getAccessKey(){return sessionStorage.getItem("bova_access_key")||""}
function setAccessKey(v){sessionStorage.setItem("bova_access_key",v)}
function getApiBase(){return(window.BOVA_API&&window.BOVA_API.baseUrl)||""}
function getDiscordUserId(){return sessionStorage.getItem("bova_discord_id")||localStorage.getItem("bova_discord_id")||""}
function setDiscordUserId(v){sessionStorage.setItem("bova_discord_id",v);localStorage.setItem("bova_discord_id",v)}
function esc(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function toast(message,type="ok"){let box=document.getElementById("toast");if(!box){box=document.createElement("div");box.id="toast";box.className="toast";document.body.appendChild(box)}box.className=`toast show ${type}`;box.textContent=message;clearTimeout(window._toastTimer);window._toastTimer=setTimeout(()=>box.classList.remove("show"),3200)}

async function apiFetch(path,options={}){
 const base=getApiBase();
 if(!base||base.includes("YOUR-RENDER")){toast("Set BOVA_API.baseUrl in js/config.js first","error");throw new Error("API URL not configured")}
 let uid=getDiscordUserId();
 if(!uid){uid=prompt("Your Discord User ID:");if(!uid)throw new Error("No Discord user ID");setDiscordUserId(uid.trim())}
 const headers={...(options.headers||{}),"X-API-Key":getAccessKey(),"X-Discord-User-Id":getDiscordUserId()};
 if(options.body){headers["Content-Type"]="application/json"}
 const res=await fetch(base.replace(/\/$/,"")+path,{...options,headers});
 const data=await res.json().catch(()=>({}));
 if(!res.ok){throw new Error(data.detail||data.error||`HTTP ${res.status}`)}
 return data;
}
function apiGet(path){return apiFetch(path)}
function apiPost(path,body){return apiFetch(path,{method:"POST",body:JSON.stringify(body)})}

async function tryUnlock(){
 const input=document.getElementById("gate-input"),uidInput=document.getElementById("gate-user-id"),err=document.getElementById("gate-error");
 const key=input.value.trim(),uid=uidInput.value.trim();
 err.style.display="none";
 if(!uid||!/^\d{5,25}$/.test(uid)){err.textContent="Enter a valid Discord User ID.";err.style.display="block";return}
 if(!key){err.textContent="Enter your access key.";err.style.display="block";return}
 setDiscordUserId(uid);setAccessKey(key);
 try{await apiFetch("/api/auth/check");sessionStorage.setItem("bova_auth","1");document.getElementById("gate").classList.add("hidden");document.getElementById("app").style.display="flex";initAll();toast("Authenticated successfully")}
 catch(e){sessionStorage.removeItem("bova_auth");err.textContent=e.message||"Authentication failed.";err.style.display="block"}
}

document.getElementById("gate-input")?.addEventListener("keydown",e=>{if(e.key==="Enter")tryUnlock()});
document.getElementById("gate-user-id")?.addEventListener("keydown",e=>{if(e.key==="Enter")tryUnlock()});
if(getDiscordUserId())document.getElementById("gate-user-id").value=getDiscordUserId();
if(sessionStorage.getItem("bova_auth")==="1"){document.getElementById("gate").classList.add("hidden");document.getElementById("app").style.display="flex";setTimeout(initAll,20)}

const TITLES={dashboard:["OVERVIEW","Dashboard"],server:["OVERVIEW","Server"],commands:["OVERVIEW","Command Center"],timestamp:["AUTOMATION","Timestamp Reminders"],autofeeds:["AUTOMATION","Auto Feeds"],meets:["ANNOUNCEMENTS","Meets"],boost:["COMMUNITY","Boost"],autorole:["COMMUNITY","Auto-Role"],tickets:["COMMUNITY","Tickets"],polls:["COMMUNITY","Polls"],dm:["PRIVATE SUPPORT","DM Inbox"],namehistory:["ARCHIVE","Name History"],embed:["TOOLS","Embed Builder"],stats:["ANALYTICS","Stats"],weblogs:["LOGGING","WebLogs"],audit:["SECURITY","Audit & Analysis"],tutorial:["GUIDE","Help & Guide"]};
function switchTab(name){document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===`panel-${name}`));const t=TITLES[name]||["BOVA CORE",name];document.getElementById("crumb").textContent=`${t[0]} / ${t[1].toUpperCase()}`;document.getElementById("page-title").textContent=t[1];document.getElementById("sidebar")?.classList.remove("open");if(name==="dashboard")loadOverview();if(name==="server")loadServerSummary();if(name==="timestamp")loadTimestampConfig();if(name==="dm")loadDmInbox();if(name==="stats")loadStats();if(name==="tickets")loadTicketLog();if(name==="audit")refreshAudit();if(name==="commands")loadCommands()}
function toggleSidebar(){document.getElementById("sidebar")?.classList.toggle("open")}
async function refreshCurrent(){const active=document.querySelector(".tab-btn.active")?.dataset.tab||"dashboard";switchTab(active);toast("Refreshed")}
document.querySelectorAll(".tab-btn").forEach(b=>b.addEventListener("click",()=>switchTab(b.dataset.tab)));
function fillSelect(sel,items,withEmpty=false){if(!sel)return;sel.innerHTML=withEmpty?'<option value="">— none —</option>':"";(items||[]).forEach(it=>{const o=document.createElement("option");o.value=typeof it==="string"?it:it.id;o.textContent=typeof it==="string"?it:(it.name||it.id);sel.appendChild(o)})}
function fillTz(sel,preferred){if(!sel)return;sel.innerHTML="";TZ_LIST.forEach(t=>{const o=document.createElement("option");o.value=t.offset;o.textContent=t.label;if(preferred!=null&&t.offset===preferred)o.selected=true;sel.appendChild(o)})}

async function loadOverview(){try{const d=await apiGet("/api/overview");document.getElementById("m-status").textContent=d.bot_ready?"ONLINE":"STARTING";document.getElementById("m-commands").textContent=d.command_count??"—";document.getElementById("m-pending").textContent=d.timestamp_reminder?.pending??"—";document.getElementById("m-dms").textContent=d.dm_inbox?.users??"—";document.getElementById("side-status").textContent=d.bot_ready?"ONLINE":"STARTING";document.getElementById("health-badge").textContent=d.bot_ready?"Operational":"Starting";document.getElementById("health-badge").className=`status-badge ${d.bot_ready?"good":"warn"}`;const uptime=Math.floor((d.uptime_seconds||0)/60);document.getElementById("health-list").innerHTML=`<div class="health-row"><span>Bot process</span><span>${d.bot_ready?"READY":"STARTING"}</span></div><div class="health-row"><span>Uptime</span><span>${uptime} min</span></div><div class="health-row"><span>SQLite documents</span><span>${d.database?.kv_documents??0}</span></div><div class="health-row"><span>Audit rows</span><span>${d.database?.audit_rows??0}</span></div>`;const ts=d.timestamp_reminder||{};document.getElementById("dash-ts-state").textContent=ts.enabled?`Enabled · ${ts.minutes} min before`:"Disabled";document.getElementById("dash-ts-detail").textContent=`${ts.pending||0} pending reminder(s) · English`;document.getElementById("dash-db").textContent=`${formatBytes(d.database?.size_bytes||0)} SQLite`;document.getElementById("dash-backup").textContent=d.backup?.last_auto?`Last auto backup: ${formatDate(d.backup.last_auto)}`:`Every ${d.backup?.interval_hours||24}h · startup backup enabled`}
 catch(e){document.getElementById("health-badge").textContent="API unavailable";document.getElementById("health-badge").className="status-badge bad"}}
function formatBytes(n){n=Number(n)||0;if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(2)} MB`}
function formatDate(s){if(!s)return"—";try{return new Date(s).toLocaleString()}catch{return s}}

async function loadTimestampConfig(){try{const d=await apiGet("/api/timestamp-reminder");document.getElementById("ts-enabled").checked=!!d.enabled;document.getElementById("ts-minutes").value=d.minutes||30;document.getElementById("ts-text").value=d.text||"";document.getElementById("ts-pending").textContent=d.pending??0;const badge=document.getElementById("ts-status-badge");badge.textContent=d.enabled?`ON · ${d.minutes} min`:`OFF`;badge.className=`status-badge ${d.enabled?"good":""}`;updateTsPreview()}
 catch(e){document.getElementById("ts-save-status").textContent=e.message}}
async function saveTimestampConfig(){const status=document.getElementById("ts-save-status");status.textContent="Saving…";try{const d=await apiPost("/api/timestamp-reminder",{enabled:document.getElementById("ts-enabled").checked,minutes:Number(document.getElementById("ts-minutes").value),text:document.getElementById("ts-text").value});status.textContent="Saved.";document.getElementById("ts-pending").textContent=d.pending??0;const badge=document.getElementById("ts-status-badge");badge.textContent=d.enabled?`ON · ${d.minutes} min`:`OFF`;badge.className=`status-badge ${d.enabled?"good":""}`;updateTsPreview();toast("Timestamp reminder configuration saved");loadOverview()}catch(e){status.textContent=e.message;toast(e.message,"error")}}
function updateTsPreview(){const enabled=document.getElementById("ts-enabled")?.checked;const minutes=Number(document.getElementById("ts-minutes")?.value||30);let text=document.getElementById("ts-text")?.value||"";text=text.replaceAll("{minutes}",String(minutes)).replaceAll("{timestamp}","1789226111").replaceAll("{jump_url}","#announcement");const out=document.getElementById("ts-preview");if(out)out.innerHTML=enabled?esc(text).replace(/&lt;t:/g,"<t:").replace(/&gt;/g,">").replace(/\n/g,"<br>").replace(/\[Open announcement\]\(#announcement\)/g,'<a>Open announcement</a>'):"Reminders are currently disabled."}

let arRoles=JSON.parse(localStorage.getItem("bova_ar_roles")||"[]");
function renderArRoles(){const box=document.getElementById("ar-role-list");if(!box)return;box.innerHTML=arRoles.map((r,i)=>`<span class="role-chip">${esc(r.emoji||"")} ${esc(r.label)} <code>${esc(r.role_id)}</code><button onclick="removeArRole(${i})">×</button></span>`).join("");localStorage.setItem("bova_ar_roles",JSON.stringify(arRoles));updateArPreview();const hint=document.getElementById("ar-cmd-hint");if(hint)hint.textContent=arRoles.length?`${arRoles.length} role button(s) ready.`:"Add roles to build the panel."}
function addArRole(){const sel=document.getElementById("ar-role-select"),id=sel.value;if(!id)return toast("Select a role","error");const name=sel.options[sel.selectedIndex]?.text||id,label=document.getElementById("ar-role-label").value.trim()||name,emoji=document.getElementById("ar-emoji-select").value||null;arRoles=arRoles.filter(r=>String(r.role_id)!==id);arRoles.push({role_id:id,label,emoji});document.getElementById("ar-role-label").value="";renderArRoles()}
function removeArRole(i){arRoles.splice(i,1);renderArRoles()}
function updateArPreview(){const box=document.getElementById("ar-preview");if(!box)return;const color=document.getElementById("ar-color")?.value||"#B450FF";box.innerHTML=`<div class="ep-title" style="border-left:4px solid ${color};padding-left:10px;font-weight:800">${esc(document.getElementById("ar-title")?.value||"")}</div><div style="margin-top:8px;white-space:pre-wrap;color:#d8d9dd">${esc(document.getElementById("ar-desc")?.value||"")}</div><div style="margin-top:15px">${arRoles.map(r=>`<span class="role-chip">${esc(r.emoji||"")} ${esc(r.label)}</span>`).join("")||'<span style="color:#777">No role buttons yet.</span>'}</div>`}
function exportArConfig(){copyText(JSON.stringify({title:document.getElementById("ar-title").value,description:document.getElementById("ar-desc").value,color:document.getElementById("ar-color").value,roles:arRoles},null,2))}
async function postArPanel(){const ch=prompt("Channel ID to post the auto-role panel:");if(!ch)return;try{const d=await apiPost("/api/autorole/panel",{channel_id:ch,title:document.getElementById("ar-title").value,description:document.getElementById("ar-desc").value,color:document.getElementById("ar-color").value,roles:arRoles});toast(`Auto-role panel posted · ${d.message_id}`)}catch(e){toast(e.message,"error")}}

function updateEmPreview(){const box=document.getElementById("em-preview");if(!box)return;const color=document.getElementById("em-color")?.value||"#00E5FF";box.style.borderLeftColor=color;box.innerHTML=`<div style="font-weight:800">${esc(document.getElementById("em-title")?.value||"Untitled embed")}</div><div style="margin-top:7px;color:#d7d8dc;white-space:pre-wrap">${esc(document.getElementById("em-desc")?.value||"")}</div>${document.getElementById("em-image")?.value?`<img src="${esc(document.getElementById("em-image").value)}" onerror="this.style.display='none'">`:""}<div style="margin-top:12px;color:#858596;font-size:9px">${esc(document.getElementById("em-footer")?.value||"")}</div>`}
async function postEmToDiscord(){try{const d=await apiPost("/api/embed",{channel_id:document.getElementById("em-channel").value,title:document.getElementById("em-title").value,description:document.getElementById("em-desc").value,color:document.getElementById("em-color").value,image_url:document.getElementById("em-image").value||null,footer:document.getElementById("em-footer").value,role_id:document.getElementById("em-role").value||null});toast(`Embed posted · ${d.message_id}`)}catch(e){toast(e.message,"error")}}
function copyEmJson(){copyText(JSON.stringify({title:document.getElementById("em-title").value,description:document.getElementById("em-desc").value,color:document.getElementById("em-color").value,image_url:document.getElementById("em-image").value||null,footer:document.getElementById("em-footer").value},null,2))}
function copyEmWebhookPayload(){copyText(JSON.stringify({content:document.getElementById("em-role").value?`<@&${document.getElementById("em-role").value}>`:null,embeds:[{title:document.getElementById("em-title").value,description:document.getElementById("em-desc").value,color:parseInt(document.getElementById("em-color").value.slice(1),16),image:document.getElementById("em-image").value?{url:document.getElementById("em-image").value}:undefined,footer:{text:document.getElementById("em-footer").value}}]},null,2))}

let mtSelectedHosts=[];
function renderMtHosts(){const box=document.getElementById("mt-hosts");if(!box)return;box.innerHTML="";C().hosts.forEach(h=>{const b=document.createElement("span");b.className=`chip ${mtSelectedHosts.includes(h)?"selected":""}`;b.textContent=h;b.onclick=()=>{mtSelectedHosts=mtSelectedHosts.includes(h)?mtSelectedHosts.filter(x=>x!==h):[...mtSelectedHosts,h];renderMtHosts();updateMtPreview()};box.appendChild(b)})}
function updateMtPreview(){const box=document.getElementById("mt-preview");if(!box)return;box.innerHTML=`<div style="font-weight:800">🚗 ${esc(document.getElementById("mt-title")?.value||"Meet")}</div><div style="margin-top:8px;color:#d7d8dc;white-space:pre-wrap">${esc(document.getElementById("mt-desc")?.value||"")}</div><div style="margin-top:13px;color:#aaa">📅 ${esc(document.getElementById("mt-date")?.value||"Date")} · ${esc(document.getElementById("mt-time")?.value||"20:00")}</div><div style="margin-top:5px;color:#aaa">👤 ${esc(mtSelectedHosts.join(", ")||"TBD")}</div>`}
function copyMtCommand(){copyText(`/meet title:${document.getElementById("mt-title").value} description:${document.getElementById("mt-desc").value} date:${document.getElementById("mt-date").value} time:${document.getElementById("mt-time").value}`)}
async function postMtToDiscord(){try{const date=document.getElementById("mt-date").value;if(!date)return toast("Select a date","error");const[y,m,d]=date.split("-");const ch=prompt("Channel ID to post the meet:");if(!ch)return;const rem=document.getElementById("mt-reminder").checked;const data=await apiPost("/api/meet",{channel_id:ch,title:document.getElementById("mt-title").value||"Meet",description:document.getElementById("mt-desc").value||"",date_time:`${d}/${m}/${y} ${document.getElementById("mt-time").value||"20:00"}`,hosts:mtSelectedHosts.join(", ")||"TBD",server:document.getElementById("mt-server").value||"",timezone_offset:parseFloat(document.getElementById("mt-tz").value||"-3"),mention_role_id:document.getElementById("mt-role").value||null,image_url:document.getElementById("mt-image").value||null,enable_reminder:rem,reminder_channel_id:rem?document.getElementById("mt-rem-ch").value:null});toast(`Meet posted · ${data.message_id}`)}catch(e){toast(e.message,"error")}}

function toggleAfMode(){const fixed=document.getElementById("af-mode")?.value==="fixed";document.getElementById("af-fixed-box").style.display=fixed?"block":"none";document.getElementById("af-interval-box").style.display=fixed?"none":"block";updateAfPreview()}
function copyAfCommand(){copyText(`/autofeed_add message:${document.getElementById("af-msg").value} channel:${document.getElementById("af-channel").value}`)}
function updateAfPreview(){const box=document.getElementById("af-preview");if(!box)return;const msg=document.getElementById("af-msg")?.value.trim()||"Sua mensagem aparecerá aqui.";const channel=document.getElementById("af-channel")?.selectedOptions?.[0]?.text||"channel";const role=document.getElementById("af-role")?.selectedOptions?.[0]?.text||"";const embed=document.getElementById("af-embed")?.checked;const title=document.getElementById("af-embed-title")?.value.trim()||"Auto Feed";const mode=document.getElementById("af-mode")?.value||"interval";let schedule=mode==="fixed"?`Daily at ${String(document.getElementById("af-hour")?.value||20).padStart(2,"0")}:${String(document.getElementById("af-minute")?.value||0).padStart(2,"0")}`:`Every ${document.getElementById("af-interval")?.value||1440} minutes`;box.innerHTML=`<div class="preview-meta">#${esc(channel)} · ${esc(schedule)}</div><div class="discord-avatar">B</div><div class="discord-body"><div class="discord-name">Bova's Bot <span>BOT</span></div>${role?`<div class="preview-mention">@${esc(role)}</div>`:""}${embed?`<div class="embed-preview af-embed-inner"><div class="ep-title">${esc(title)}</div><div class="discord-msg">${esc(msg)}</div></div>`:`<div class="discord-msg">${esc(msg)}</div>`}</div>`}
async function postAfToDiscord(){try{const mode=document.getElementById("af-mode").value;const body={message:document.getElementById("af-msg").value,channel_id:document.getElementById("af-channel").value,role_id:document.getElementById("af-role").value||null,mode,use_embed:document.getElementById("af-embed").checked,embed_title:document.getElementById("af-embed-title").value||null};if(mode==="fixed"){body.fixed_hour=Number(document.getElementById("af-hour").value);body.fixed_minute=Number(document.getElementById("af-minute").value)}else body.interval_minutes=Number(document.getElementById("af-interval").value);const d=await apiPost("/api/autofeed",body);toast(`Auto feed created · #${d.id}`)}catch(e){toast(e.message,"error")}}

async function loadTicketLog(){const el=document.getElementById("ticket-log-list");if(!el)return;el.innerHTML="<div class='skeleton'></div>";try{const d=await apiGet("/api/tickets");el.innerHTML=(d.entries||[]).map(e=>`<div class="list-item"><strong>[${esc(e.kind||"")}] ${esc(e.subject||"")}</strong><div class="muted">${esc(e.user_id||"")} · ${esc(formatDate(e.created_at))} · #${esc(e.id||"")}</div><p>${esc((e.body||"").slice(0,300))}</p></div>`).join("")||'<div class="muted">No submissions yet.</div>'}catch(e){el.innerHTML=`<div class="muted">${esc(e.message)}</div>`}}

let pollOptions=["",""];
function normalizePollOptions(){pollOptions=[...document.querySelectorAll(".poll-option-input")].map(x=>x.value)}
function renderPollOptions(){const box=document.getElementById("poll-options-list");if(!box)return;box.innerHTML=pollOptions.map((v,i)=>`<div class="dynamic-option"><span class="option-index">${i+1}</span><input class="poll-option-input" value="${esc(v.trim())}" maxlength="80" placeholder="Option ${i+1}" oninput="pollOptions[${i}]=this.value;updatePollPreview()">${i>1?`<button type="button" class="remove-option-btn" onclick="removePollOption(${i})">×</button>`:""}</div>`).join("")}
function addPollOption(){normalizePollOptions();if(pollOptions.length>=10)return toast("Maximum 10 options","error");pollOptions.push("");renderPollOptions();document.querySelectorAll(".poll-option-input")[pollOptions.length-1]?.focus();updatePollPreview()}
function removePollOption(i){normalizePollOptions();if(pollOptions.length<=2)return;pollOptions.splice(i,1);renderPollOptions();updatePollPreview()}
function updatePollPreview(){const box=document.getElementById("poll-preview");if(!box)return;normalizePollOptions();const title=document.getElementById("poll-title")?.value.trim()||"Poll question";const desc=document.getElementById("poll-desc")?.value.trim()||"Optional context";const color=document.getElementById("poll-color")?.value||"#B450FF";const single=document.getElementById("poll-single")?.checked;const hours=Number(document.getElementById("poll-hours")?.value)||0;const opts=pollOptions.map(x=>x.trim()).filter(Boolean);box.innerHTML=`<div class="discord-preview poll-discord-preview"><div class="discord-avatar">B</div><div class="discord-body"><div class="discord-name">Bova's Bot <span>BOT</span></div><div class="poll-embed" style="border-left-color:${esc(color)}"><div class="poll-title">📊 ${esc(title)}</div>${desc?`<div class="poll-desc">${esc(desc)}</div>`:""}<div class="poll-preview-options">${opts.map((o,i)=>`<div class="poll-preview-option"><span>${i+1}</span>${esc(o)}</div>`).join("")||'<div class="preview-empty">Add at least 2 options</div>'}</div><div class="poll-preview-footer">Total votes: 0${single?" · 1 vote per user":""}${hours?` · Closes in ${hours}h`:""}</div></div></div></div>`}
async function postPoll(){try{normalizePollOptions();const options=pollOptions.map(x=>x.trim()).filter(Boolean);if(options.length<2)return toast("Add at least 2 options","error");const d=await apiPost("/api/poll",{channel_id:document.getElementById("poll-channel").value,title:document.getElementById("poll-title").value,description:document.getElementById("poll-desc").value,options,single_vote:document.getElementById("poll-single").checked,hours:Number(document.getElementById("poll-hours").value)||null,color:document.getElementById("poll-color").value});document.getElementById("poll-status").textContent=`Created poll #${d.id}`;toast(`Poll created · #${d.id}`)}catch(e){document.getElementById("poll-status").textContent=e.message;toast(e.message,"error")}}

async function loadDmInbox(){const el=document.getElementById("dm-list");if(!el)return;el.innerHTML="<div class='skeleton'></div>";try{const d=await apiGet("/api/dm/inbox");document.getElementById("dm-auto-enabled").checked=!!d.auto_response_enabled;document.getElementById("dm-auto-text").value=d.auto_response_text||"";el.innerHTML=(d.conversations||[]).map(x=>`<div class="inbox-item" onclick="loadDmHistory('${esc(x.user_id)}')"><div class="inbox-avatar">✉</div><div class="inbox-meta"><strong>${esc(x.user_id)}</strong><p>${esc(x.last_content||"Attachment / no text")}</p><small>${x.message_count} messages · ${esc(formatDate(x.last_timestamp))}</small></div></div>`).join("")||'<div class="muted">No DM conversations recorded.</div>'}catch(e){el.innerHTML=`<div class="muted">${esc(e.message)}</div>`}}
async function loadDmHistory(uid){const card=document.getElementById("dm-history-card");try{const d=await apiGet(`/api/dm/history/${encodeURIComponent(uid)}`);document.getElementById("dm-history-title").textContent=`DM history · ${uid}`;document.getElementById("dm-history").innerHTML=(d.messages||[]).map(m=>`<div class="chat-msg ${m.direction==="out"?"out":""}"><small>${m.direction==="out"?"BOVA'S BOT":"USER"} · ${esc(formatDate(m.timestamp))}</small>${esc(m.content||"(attachment / no text)")}${m.attachments?.length?`\n📎 ${m.attachments.length} attachment(s)`:""}</div>`).join("")||'<div class="muted">No messages.</div>';card.style.display="block";card.dataset.userId=uid;card.scrollIntoView({behavior:"smooth",block:"start"})}catch(e){toast(e.message,"error")}}
async function sendDmReply(){const card=document.getElementById("dm-history-card"),uid=card.dataset.userId,text=document.getElementById("dm-reply-text").value.trim();if(!uid||!text)return toast("Select a conversation and write a reply","error");try{await apiPost("/api/dm/reply",{user_id:uid,message:text});document.getElementById("dm-reply-text").value="";document.getElementById("dm-reply-status").textContent="Reply sent.";await loadDmHistory(uid);toast("DM reply sent")}catch(e){document.getElementById("dm-reply-status").textContent=e.message;toast(e.message,"error")}}
async function saveDmAuto(){try{const d=await apiPost("/api/dm/auto",{enabled:document.getElementById("dm-auto-enabled").checked,text:document.getElementById("dm-auto-text").value});document.getElementById("dm-auto-status").textContent=d.enabled?"Automatic response enabled.":"Automatic response disabled.";toast("DM auto-response saved")}catch(e){document.getElementById("dm-auto-status").textContent=e.message;toast(e.message,"error")}}

async function loadServerSummary(){const el=document.getElementById("server-summary");if(!el)return;el.innerHTML="<div class='skeleton'></div>";try{const d=await apiGet("/api/server/summary");el.innerHTML=`<div class="server-kpis"><div class="server-kpi"><strong>${esc(d.member_count)}</strong><small>members</small></div><div class="server-kpi"><strong>${esc(d.text_channels)}</strong><small>text channels</small></div><div class="server-kpi"><strong>${esc(d.voice_channels)}</strong><small>voice channels</small></div><div class="server-kpi"><strong>L${esc(d.boost_tier)}</strong><small>${esc(d.boosts)} boosts</small></div></div><strong>${esc(d.name)}</strong><div class="muted">ID ${esc(d.id)} · ${esc(d.humans)} humans · ${esc(d.bots)} bots · ${esc(d.roles_count)} roles</div><div style="margin-top:14px"><strong>Top roles</strong>${(d.roles||[]).slice(0,12).map(r=>`<div class="health-row"><span>${esc(r.name)}</span><span>${r.members} members</span></div>`).join("")}</div>`}catch(e){el.innerHTML=`<div class="muted">${esc(e.message)}</div>`}}

async function loadStats(){const el=document.getElementById("stats-summary");if(!el)return;try{const d=await apiGet("/api/stats/summary");const top=(d.top_messages||[]).map(x=>`<div class="health-row"><span>${esc(x[0])}</span><span>${x[1]}</span></div>`).join("");el.innerHTML=`<div class="server-kpis"><div class="server-kpi"><strong>${d.joins||0}</strong><small>joins</small></div><div class="server-kpi"><strong>${d.leaves||0}</strong><small>leaves</small></div><div class="server-kpi"><strong>${Object.values(d.hourly||{}).reduce((a,b)=>a+Number(b||0),0)}</strong><small>tracked messages</small></div><div class="server-kpi"><strong>${Object.keys(d.weekday||{}).length}</strong><small>active weekdays</small></div></div><strong>Top tracked message authors</strong>${top||'<div class="muted">No data yet.</div>'}`}catch(e){el.textContent=e.message}}

const COMMAND_META={
 automation:["autofeed_add","autofeed_list","autofeed_remove","autofeed_toggle","timestamp_reminder_config","timestamp_reminder_status"],
 community:["autorole_add","autorole_config","autorole_list","autorole_panel","autorole_remove","birthday_announce_channel","birthday_panel","boost_config","invitepanel","meet","poll","poll_end","poll_list","sticky_clear","sticky_set","ticket_list","ticket_panel","ticket_setup","welcome_config","welcome_test","dm_inbox","dm_history","dm_reply","dm_auto_response"],
 moderation:["delete","purge"],
 utility:["avatar","help","info","membercount","servericon","serverinfo","timestamp","userinfo","say","panel","commands_panel"],
 analytics:["namehistory","namehistory_export","stats","topmedia","week_summary"],
 system:["backup_export","backup_hint","backup_now","db_status","weblogs_config"],
 support:["cmd_add","cmd_list","cmd_remove","run"]
};
const FALLBACK_COMMANDS=[
 ["autofeed_add","Add a scheduled auto-feed message"],["autofeed_list","List auto-feeds"],["autofeed_remove","Remove an auto-feed by ID"],["autofeed_toggle","Enable/disable an auto-feed"],
 ["autorole_add","Add a role to the auto-role panel"],["autorole_config","Set auto-role embed title and description"],["autorole_list","List configured auto-roles"],["autorole_panel","Post the auto-role panel"],["autorole_remove","Remove an auto-role"],
 ["avatar","Show a user avatar"],["backup_export","Export stored bot data"],["backup_hint","Explain backup and restore"],["backup_now","Force a SQLite backup"],["birthday_announce_channel","Set the birthday announcement channel"],["birthday_panel","Post the birthday panel"],["boost_config","Configure boost thank-you"],
 ["cmd_add","Create a custom command"],["cmd_list","List custom commands"],["cmd_remove","Remove a custom command"],["commands_panel","Post the Discord command hub"],["db_status","Show SQLite status"],["delete","Delete a message by ID"],
 ["dm_auto_response","Configure automatic DM acknowledgement"],["dm_history","View a user's DM history"],["dm_inbox","Show recent DM contacts"],["dm_reply","Reply through the bot"],["help","Open the Discord help panel"],["info","Show bot/server/user information"],["invitepanel","Post the invite request panel"],["meet","Post a car meet announcement"],
 ["membercount","Show server member count"],["namehistory","Show member name history"],["namehistory_export","Export name history"],["panel","Get the private web panel link"],["ping","Show bot latency"],["poll","Create a live poll"],["poll_end","Force-end a poll"],["poll_list","List active polls"],["purge","Delete recent messages"],["run","Run a custom command"],["say","Make the bot say something"],["servericon","Show server icon"],["serverinfo","Show server information"],["stats","Show activity statistics"],["sticky_clear","Remove the sticky message"],["sticky_set","Set a sticky message"],["ticket_list","List recent submissions"],["ticket_panel","Post the ticket/suggestion/report panel"],["ticket_setup","Configure ticket channels"],["timestamp","Generate a Discord timestamp"],["timestamp_reminder_config","Configure automatic timestamp reminders"],["timestamp_reminder_status","Show timestamp reminder status"],["topmedia","Show top reacted media"],["userinfo","Show detailed member information"],["weblogs_config","Configure WebLogs toggles"],["week_summary","Show the weekly activity snapshot"],["welcome_config","Configure welcome automation"],["welcome_test","Test the welcome DM"]
].map(x=>({name:x[0],description:x[1]}));
let commandData=FALLBACK_COMMANDS;
function commandCategory(name){for(const [cat,names] of Object.entries(COMMAND_META))if(names.includes(name))return cat;return"utility"}
function isStaffCommand(name){return ["backup_export","backup_now","cmd_add","cmd_remove","delete","dm_auto_response","dm_history","dm_inbox","dm_reply","panel","purge","say","ticket_list","ticket_setup","namehistory_export","weblogs_config","timestamp_reminder_config"].includes(name)}
async function loadCommands(){try{const d=await apiGet("/api/commands");if(Array.isArray(d.commands)&&d.commands.length)commandData=d.commands}catch(e){}renderCommands()}
function renderCommands(){const list=document.getElementById("command-list");if(!list)return;const q=(document.getElementById("command-search")?.value||"").toLowerCase();const filter=document.getElementById("command-filter")?.value||"all";const rows=commandData.filter(c=>(!q||`${c.name} ${c.description}`.toLowerCase().includes(q))&&(filter==="all"||commandCategory(c.name)===filter));document.getElementById("command-count").textContent=`${commandData.length} commands`;list.innerHTML=rows.map(c=>`<div class="command-card"><div class="cmd-top"><code>/${esc(c.name)}</code><span class="tag">${esc(commandCategory(c.name))}</span>${isStaffCommand(c.name)?'<span class="tag staff">staff</span>':''}</div><p>${esc(c.description||"")}</p></div>`).join("")||'<div class="muted">No commands match your search.</div>'}

function renderNameHistory(){const raw=document.getElementById("nh-json")?.value||"",out=document.getElementById("nh-out");if(!out)return;try{const data=JSON.parse(raw),members=data.members||data;out.innerHTML=Object.values(members).slice(0,80).map(m=>{const names=(m.names||[]).slice(-5).map(n=>n.reason==="rename"?`${esc(n.previous_display_name||"?")} → <strong>${esc(n.display_name||"?")}</strong>`:`first: <strong>${esc(n.display_name||"?")}</strong>`).join("<br>");return`<div class="archive-card"><strong>${esc(m.display_name||m.username||m.user_id)}</strong> <code>${esc(m.user_id||"")}</code><div class="muted" style="margin-top:5px">${names||"—"}</div></div>`}).join("")||'<div class="muted">No members in file.</div>'}catch(e){out.innerHTML=`<div class="muted">Invalid JSON: ${esc(e.message)}</div>`}}

async function refreshAudit(){try{const d=await apiGet("/api/overview");document.getElementById("audit-db").innerHTML=`<div class="server-kpis"><div class="server-kpi"><strong>${formatBytes(d.database?.size_bytes||0)}</strong><small>DB size</small></div><div class="server-kpi"><strong>${d.database?.kv_documents||0}</strong><small>KV docs</small></div><div class="server-kpi"><strong>${d.database?.audit_rows||0}</strong><small>audit rows</small></div><div class="server-kpi"><strong>${d.backup?.interval_hours||24}h</strong><small>backup interval</small></div></div><div class="health-row"><span>Last automatic backup</span><span>${esc(formatDate(d.backup?.last_auto))}</span></div><div class="health-row"><span>Backup channel</span><span>${esc(d.backup?.channel_id||"not configured")}</span></div>`;const a=await apiGet("/api/audit");document.getElementById("audit-log").innerHTML=(a.entries||[]).map(e=>`<div class="audit-row"><strong>${esc(e.action||"")}</strong> · ${esc(e.ts||"")} · actor ${esc(e.actor_id||"—")} · ${e.success?"OK":"FAIL"}<br>${esc(JSON.stringify(e.detail||{}).slice(0,220))}</div>`).join("")||'<div class="muted">No audit entries.</div>'}catch(e){document.getElementById("audit-log").textContent=e.message}}

function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast("Copied to clipboard")).catch(()=>prompt("Copy:",text))}
function initAll(){const cfg=C();fillSelect(document.getElementById("ar-role-select"),cfg.roles);fillSelect(document.getElementById("ar-emoji-select"),cfg.emojis);fillSelect(document.getElementById("em-channel"),cfg.channels);fillSelect(document.getElementById("em-role"),cfg.roles,true);fillSelect(document.getElementById("mt-server"),cfg.servers);fillSelect(document.getElementById("mt-role"),cfg.roles,true);fillSelect(document.getElementById("mt-rem-ch"),cfg.channels);fillSelect(document.getElementById("af-channel"),cfg.channels);fillSelect(document.getElementById("af-role"),cfg.roles,true);fillSelect(document.getElementById("poll-channel"),cfg.channels);fillTz(document.getElementById("mt-tz"),-3);fillTz(document.getElementById("af-tz"),-3);const today=new Date().toISOString().slice(0,10);if(!document.getElementById("mt-date").value)document.getElementById("mt-date").value=today;renderArRoles();renderMtHosts();updateArPreview();updateEmPreview();updateMtPreview();toggleAfMode();renderPollOptions();updatePollPreview();updateAfPreview();loadOverview();loadTimestampConfig();loadCommands()}
